<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ZhuoDazi\ZhuoDazi.csproj" />
    <None Include="..\..\ZhuoDazi\App.xaml" Link="App.xaml.source" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
